In [11]:
#importamos librerias requeridas
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
#Carga desde un archivo .xlsx sin indice
df = pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
df

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [13]:
#Verificamos informacion de dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        162 non-null    object
 1   NOMBRE             163 non-null    object
 2   FACTURA            163 non-null    object
 3   FECHA_FACTURA      163 non-null    datetime64[ns]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[ns]
 5   MONTO ADEUDADO     163 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 7.8+ KB

In [5]:
#Filtro por objetos
filtro1=df[(df["NOMBRE"]=="INDUSTRIAS LANCERMEX")]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [6]:
#Filtro por filas
#filtro2= df.iloc[3:11, : ]
filtro2 = df.iloc [ [ 2, 5], :]
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00

In [7]:
#Filtro por comnas
#filtro3=df.iloc[ : , 1:3] #columnas consecutivas
filtro3=df.iloc[ : , [1,4,5]] #columanas no consecutivas
filtro3

,NOMBRE,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,DONGA HWASUNG MEXICO,2023-03-26,97485.94
1,DONGA HWASUNG MEXICO,2023-04-13,97485.94
2,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,2023-04-13,64916.21
3,INDUSTRIAS LANCERMEX,2023-03-25,52715.74
4,HELVEX,2023-04-03,50639.80
...,...,...,...
159,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,2023-01-31,56.00
160,PÚBLICO EN GENERAL,2023-03-07,45.00
161,PÚBLICO EN GENERAL,2023-03-09,40.00
162,PÚBLICO EN GENERAL,2023-03-09,24.01
163,FISHERS QUERETARO,2022-05-27,19.94

In [10]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx' , index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

**Paso2 : Aplicamos filtro de filas vs columnas**

In [15]:
filtro4=df1.loc[["HELVEX" , "DONGA HWASUNG MEXICO"] ,["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [16]:
#filtro por cola
filtro6=df.tail()
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

**FILTRO BASICOS PARA VARIABLE CUANTITATIVOS**

In [14]:

#Filtro por comparacion
filtro7 = df[df["MONTO ADEUDADO"] < 7000]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
62,2995,FRESCOS DON GU,F40371,2023-03-15,2023-03-23,6840.66
63,466,DEACERO,F40149,2023-02-15,2023-04-16,6820.80
64,3228,KERN LIEBERS MEXICO,F40143,2023-02-14,2023-02-14,6612.00
65,8251,PQUISEM,F40346,2023-03-13,2023-03-21,6496.00
66,322,EDGAR GARCIA HERNANDEZ,F40229,2023-02-24,2023-03-11,6438.19
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

**FILTROS BASICOS CON CONECTORES LOGICOS**

In [16]:
#Filtro y 
filtro8=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

#Filtro O
filtro9=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro9

#FILTRO NOT
filtro10=df[~(df["FECHA_FACTURA"]== "2023-03-14")]
filtro10

filtro10.to_csv("Entregable1.csv")